#!/bin/bash
cabal update
cabal install vector
cabal install hashtables
cabal install conduit
cabal install zlib-conduit
cabal install data-binary-ieee754
cabal install json
cabal install monadlib
cabal install enumerator

# exec { "curl -o ~/flex_sdk_4.6.zip http://download.macromedia.com/pub/flex/sdk/flex_sdk_4.6.zip":
#   creates => "~/flex_sdk_4.6.zip"
# }
